src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Table(name="users")
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=20, unique=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="smallint")
     */
    private $id_user;

    /**
     * @ORM\Column(type="smallint")
     */
    private $id_org;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $password;

    /**
     * @Assert\NotBlank()
     * @Assert\Length(max=4096)
     */
    private $plainPassword;

    /**
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Organization", inversedBy="users")
     * @ORM\JoinColumn(name="id_org", referencedColumnName="id", nullable=false)
     */
    private $organization;

    public function __construct()
    {
        $this->isActive = true;
        // $this->salt = md5(uniqid('', true));
    }

    public function getUsername()
    {
        return $this->phone;
    }

    public function getSalt()
    {
        return null;
    }

    public function getRoles()
    {
        return array('ROLE_USER');
    }

    public function eraseCredentials()
    {
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getIdUser(): ?int
    {
        return $this->id_user;
    }

    public function setIdUser(int $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    /*
    public function getIdOrg(): ?int
    {
        return $this->id_org;
    }

    public function setIdOrg(int $id_org): self
    {
        $this->id_org = $id_org;

        return $this;
    }
    */

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    public function setPlainPassword($password)
    {
        $this->plainPassword = $password;
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->phone,
            $this->password,
            // $this->salt,
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->phone,
            $this->password,
            // $this->salt
            ) = unserialize($serialized, array('allowed_classes' => false));
    }


    public function getOrganization(): ?Organization
    {
        return $this->organization;
    }

    public function setOrganization(?Organization $organization): self
    {
        $this->organization = $organization;

        return $this;
    }

    public function getOrgName()
    {
        return $this->getOrganization()->getName();
    }
}

src/Controller/MainController.php
<?php
/**
 * Created by PhpStorm.
 * User: kseni
 * Date: 12.06.2020
 * Time: 14:17
 */

namespace App\Controller;


use App\Entity\User;
use App\Entity\Organization;
use App\Form\SignupForm;
use App\Helper\Validator;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class MainController extends AbstractController
{
    /**
     * @Route("/", name="app_homepage")
     */
    public function homepage()
    {
        return $this->render('main/home.html.twig');
    }

    /**
     * @Route("/signup", name="signup")
     */
    public function signup(Request $request, UserPasswordEncoderInterface $encoder)
    {
        if ($this->isGranted('ROLE_USER'))
            return $this->redirectToRoute('profile');

        $userRepository = $this->getDoctrine()
            ->getRepository(User::class);

        // Список пользователей для поля "Кто пригласил"
        $users = $userRepository->getUserList();

        if ($request->isMethod('POST')) {

            // Данные с формы
            $userArray = $request->request->get('user');

            $form = new SignupForm($userArray);
            if ($form->validate()) {
                $foundUser = $userRepository->findOneBy(['phone' => $form->phone]);
                if ($foundUser) {
                    $this->addFlash('error', 'Пользователь с таким номером телефона уже зарегистрирован.');
                } else {
                    $entityManager = $this->getDoctrine()->getManager();

                    // Проверяем, есть ли организация в БД
                    $org = $this->getDoctrine()
                        ->getRepository(Organization::class)
                        ->findOneByName($form->org);

                    $entityManager->getConnection()->beginTransaction();
                    try {
                        // Если такой организации еще нет, добавляем ее
                        if (!$org) {
                            $org = new Organization();
                            $org->setName($form->org);
                            $entityManager->persist($org);
                            $entityManager->flush();
                        }

                        // Добавляем пользователя
                        $user = new User();
                        $user->setFirstName($form->first_name)
                            ->setLastName($form->last_name)
                            ->setPhone($form->phone)
                            ->setIdUser($form->id_user) // TODO: проверить, что пользователь с таким id существует
                            ->setOrganization($org)
                            ->setPassword($encoder->encodePassword($user, $form->password));

                        $entityManager->persist($user);
                        $entityManager->flush();
                        $entityManager->getConnection()->commit();
                        $this->addFlash('success', 'Вы успешно зарегистрированы!');
                        return $this->redirectToRoute('app_homepage');
                    } catch (\Exception $ex) {
                        $entityManager->getConnection()->rollBack();
                        $this->addFlash('error', 'Ошибка. Попробуйте позже.');
                    }
                }

            } else {
                $this->addFlash('error', 'Поля формы заполнены неверно.');
            }
        }
        return $this->render('main/signup.html.twig', [
            'userArray' => $userArray ?? [],
            'userList' => $users
        ]);
    }

    /**
     * @Route("/profile", name="profile")
     */
    public function profile()
    {
        $currentUser = $this->getUser();
        // Список пользователей для поля "Кто пригласил"
        $users = $this->getDoctrine()
            ->getRepository(User::class)
            ->getUserList($currentUser->getId());

        return $this->render('main/profile.html.twig', [
            'userList' => $users
        ]);
    }

    /**
     * @Route("/profile-save", name="profile-save")
     */
    public function profileSave(Request $request)
    {
        if (!$request->isXmlHttpRequest()) {
            return new JsonResponse([
                'status' => 'error',
                'message' => 'Ошибка'
            ], 400);
        }

        if ($request->isMethod('POST')) {
            $firstName = $request->request->get('first_name');
            $lastName = $request->request->get('last_name');
            $newPhone = $request->request->get('phone');
            $newOrg = $request->request->get('org');
            $newIdUser = $request->request->get('id_user');
            if (!Validator::test('simpleString', $firstName) || !Validator::test('simpleString', $lastName)) {
                return new JsonResponse([
                    'status' => 'error',
                    'errorMsg' => 'Неправильно заполнены Имя / Фамилия'
                ]);
            }
            if (!Validator::test('simplePhone', $newPhone)) {
                return new JsonResponse([
                    'status' => 'error',
                    'errorMsg' => 'Неправильно заполнено поле Телефон'
                ]);
            }

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->getConnection()->beginTransaction();
            try {
                $currentUser = $this->getUser();

                $userRepository = $this->getDoctrine()
                    ->getRepository(User::class);

                // Если организация поменялась, проверяем, если она в базе.
                // Если нет, добавляем
                if ($newOrg !== $currentUser->getOrgName()) {
                    $org = $this->getDoctrine()
                        ->getRepository(Organization::class)
                        ->findOneByName($newOrg);

                    if (!$org) {
                        $org = new Organization();
                        $org->setName($newOrg);
                        $entityManager->persist($org);
                        $entityManager->flush();
                    }
                    $currentUser->setOrganization($org);
                }

                if ($newIdUser != $currentUser->getIdUser()) {
                    $foundUser = $userRepository->findOneBy(['id' => $newIdUser]);
                    if ($foundUser) {
                        $currentUser->setIdUser($newIdUser);
                    }
                }
                if ($newPhone != $currentUser->getPhone()) {
                    $foundUser = $userRepository->findOneBy(['phone' => $newPhone]);
                    if (!$foundUser) {
                        $currentUser->setPhone($newPhone);
                    } else {
                        $entityManager->getConnection()->rollBack();
                        return new JsonResponse([
                            'status' => 'error',
                            'errorMsg' => 'Пользователь с таким номером телефона уже есть в базе.'
                        ]);
                    }
                }

                $currentUser->setFirstName($firstName);
                $currentUser->setLastName($lastName);

                $entityManager->persist($currentUser);
                $entityManager->flush();
                $entityManager->getConnection()->commit();

                return new JsonResponse([
                    'status' => 'ok',
                    'data' => $firstName
                ]);
            } catch (Exception $ex) {
                $entityManager->getConnection()->rollBack();
                return new JsonResponse([
                    'status' => 'error',
                    'errorMsg' => 'При сохранении данных возникла ошибка.'
                ]);
            }
        }
    }

    /**
     * @Route("/get-organizations")
     */
    public function getOrgs(Request $request)
    {
        if (!$request->isXmlHttpRequest()) {
            return new JsonResponse([
                'status' => 'error',
                'message' => 'Ошибка'
            ], 400);
        }

        $orgs = $this->getDoctrine()
            ->getRepository(Organization::class)
            ->getOrgArray();

        if ($request->isMethod('POST')) {
            return new JsonResponse([
                'status' => 'ok',
                'orgs' => $orgs
            ]);
        }
    }
}

templates/main/home.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Привет!</h1>
    {% for message in app.flashes('success') %}
        <div class="alert alert-success" style="max-width: 600px;">
            {{ message }}
        </div>
    {% endfor %}
    <p>Этот сайт пока почти ничего не умеет :(</p>
    <p>Вы можете:</p>
    <ul class="fancy-list">
        <li><a href="{{ path('signup') }}" class="a-anim">Зарегистрироваться</a></li>
        <li>или <a href="{{ path('app_login') }}" class="a-anim">войти в личный кабинет</a></li>
    </ul>

{% endblock %}

templates/main/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Личный кабинет{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/easy-autocomplete.min.css') }}">
{% endblock %}

{% block body %}
    <div class="form-wrapper signup-form-wrapper">
        <div id="successMsg" class="alert alert-success hidden">
            Информация сохранена.
        </div>
        <div id="errorMsg" class="alert alert-danger hidden"></div>
        <form method="post" id="profileForm">
            <div class="row form-group">
                <div class="col-md-4 col-12">
                    <i class="fas fa-user"></i>
                    <label for="inputFirstName">Имя</label>
                </div>
                <div class="col-md-8 col-12">
                    <input id="inputFirstName" name="first_name" value="{{ app.user.firstName }}" type="text" class="form-control">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-4 col-12">
                    <i class="far fa-user"></i>
                    <label for="inputLastName">Фамилия</label>
                </div>
                <div class="col-md-8 col-12">
                    <input id="inputLastName" name="last_name" value="{{ app.user.lastName }}" type="text" class="form-control">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-4 col-12">
                    <i class="fas fa-mobile-alt"></i>
                    <label for="inputPhone">Телефон</label>
                </div>
                <div class="col-md-8 col-12">
                    <input id="inputPhone" name="phone" value="{{ app.user.phone }}" type="text" class="form-control">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-4 col-12">
                    <i class="fas fa-user-friends"></i>
                    <label for="inputIdUser">Кто пригласил</label>
                </div>
                <div class="col-md-8 col-12">
                    <select name="id_user" id="inputIdUser" class="form-control">
                        {% for user in userList %}
                            <option value="{{ user.Id }}" {% if app.user.idUser == user.Id %} selected {% endif %}>{{ user.FirstName|e }} {{ user.LastName|e  }} </option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-4 col-12">
                    <i class="far fa-building"></i>
                    <label for="inputIdOrg">Организация</label>
                </div>
                <div class="col-md-8 col-12">
                    <input id="inputIdOrg" value="{{ app.user.organization.name }}" name="org" type="text" class="form-control">
                    <input id="idOrg" type="hidden" name="id_org" value="{{ app.user.organization.id }}">
                </div>
            </div>
            <button id="btnSave" class="btn btn-info">Сохранить</button>
        </form>
    </div>
    <div id="results"></div>
{% endblock %}


{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/main.js') }}"></script>
    <script src="{{ asset('js/profile.js') }}"></script>
    <script src="{{ asset('js/jquery.easy-autocomplete.min.js') }}"></script>
{% endblock %}

templates/main/signup.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/easy-autocomplete.min.css') }}">
{% endblock %}

{% block body %}
    <h1>Регистрация пользователя</h1>
    <div class="form-wrapper signup-form-wrapper">
        {% for message in app.flashes('success') %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endfor %}
        {% for message in app.flashes('error') %}
            <div class="alert alert-danger">
                {{ message }}
            </div>
        {% endfor %}
        <form action="{{ path('signup') }}" method="post" id="signupForm">
            <div class="row form-group">
                <div class="col-md-4 col-12">
                    <i class="fas fa-user"></i>
                    <label for="inputFirstName">Имя</label>
                </div>
                <div class="col-md-8 col-12">
                    <input id="inputFirstName" name="user[first_name]" value="{{ userArray.first_name|default('') }}" type="text" class="form-control">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-4 col-12">
                    <i class="far fa-user"></i>
                    <label for="inputLastName">Фамилия</label>
                </div>
                <div class="col-md-8 col-12">
                    <input id="inputLastName" name="user[last_name]" value="{{ userArray.last_name|default('') }}" type="text" class="form-control">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-4 col-12">
                    <i class="fas fa-mobile-alt"></i>
                    <label for="inputPhone">Телефон</label>
                </div>
                <div class="col-md-8 col-12">
                    <input id="inputPhone" name="user[phone]" value="{{ userArray.phone|default('') }}" type="text" class="form-control">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-4 col-12">
                    <i class="fas fa-user-friends"></i>
                    <label for="inputIdUser">Кто пригласил</label>
                </div>
                <div class="col-md-8 col-12">
                    <select name="user[id_user]" id="inputIdUser" class="form-control">
                        <option value="0"></option>
                        {% for user in userList %}
                            <option value="{{ user.Id }}" {% if userArray.id_user is defined and userArray.id_user == user.Id %} selected {% endif %}>{{ user.FirstName|e }} {{ user.LastName|e  }} </option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-4 col-12">
                    <i class="far fa-building"></i>
                    <label for="inputIdOrg">Организация</label>
                </div>
                <div class="col-md-8 col-12">
                    <input id="inputIdOrg" value="{{ userArray.org|default('') }}" name="user[org]" type="text" class="form-control">
                    <input id="idOrg" type="hidden" name="user[id_org]" value="">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-4 col-12">
                    <i class="fas fa-lock"></i>
                    <label for="inputPassword">Пароль</label>
                </div>
                <div class="col-md-8 col-12">
                    <input id="inputPassword" name="user[password]" type="password" class="form-control">
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-4 col-12">
                    <i class="fas fa-lock"></i>
                    <label for="inputPassword2">Подтвердите пароль</label>
                </div>
                <div class="col-md-8 col-12">
                    <input id="inputPassword2" name="user[password2]" type="password" class="form-control">
                </div>
            </div>
            <button type="submit" class="btn btn-info">Зарегистрироваться</button>
        </form>
    </div>


{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/main.js') }}"></script>
    <script src="{{ asset('js/jquery.easy-autocomplete.min.js') }}"></script>
{% endblock %}