src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Table(name="users")
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=20, unique=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="smallint")
     */
    private $id_user;

    /**
     * @ORM\Column(type="smallint")
     */
    private $id_org;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $password;

    /**
     * @Assert\NotBlank()
     * @Assert\Length(max=4096)
     */
    private $plainPassword;

    /**
     * @ORM\Column(name="is_active", type="boolean")
     */
    private $isActive;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Organization", inversedBy="users")
     * @ORM\JoinColumn(name="id_org", referencedColumnName="id", nullable=false)
     */
    private $organization;

    public function __construct()
    {
        $this->isActive = true;
        // $this->salt = md5(uniqid('', true));
    }

    public function getUsername()
    {
        return $this->phone;
    }

    public function getSalt()
    {
        return null;
    }

    public function getRoles()
    {
        return array('ROLE_USER');
    }

    public function eraseCredentials()
    {
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getIdUser(): ?int
    {
        return $this->id_user;
    }

    public function setIdUser(int $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    /*
    public function getIdOrg(): ?int
    {
        return $this->id_org;
    }

    public function setIdOrg(int $id_org): self
    {
        $this->id_org = $id_org;

        return $this;
    }
    */

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    public function setPlainPassword($password)
    {
        $this->plainPassword = $password;
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->phone,
            $this->password,
            // $this->salt,
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->phone,
            $this->password,
            // $this->salt
            ) = unserialize($serialized, array('allowed_classes' => false));
    }


    public function getOrganization(): ?Organization
    {
        return $this->organization;
    }

    public function setOrganization(?Organization $organization): self
    {
        $this->organization = $organization;

        return $this;
    }

    public function getOrgName()
    {
        return $this->getOrganization()->getName();
    }
}

templates/base.html.twig
<!doctype html>
<html lang="en">

<head>
    <title>{% block title %}Symfony Test Task{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{{ asset('images/favicon.ico') }}" type="image/png">

    {% block stylesheets %}
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" rel="stylesheet">
        <link rel="stylesheet" href="{{ asset('css/style.css') }}">
    {% endblock %}
</head>

<body>

<header>
    <nav class="navbar navbar-expand-md navbar-dark bg-green">
        <a class="navbar-brand" href="/"><img src="{{ asset('images/blue-book.png') }}" alt="book" width="50"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ path('app_homepage') }}"><i class="fas fa-home"></i> На главную</a>
                </li>
                {% if app.user %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('profile') }}"><i class="fas fa-id-card"></i> Личный кабинет</a>
                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if app.user %}
                    <li class="nav-item">
                        <span>Привет, {{ app.user.firstName }}!</span>
                    </li>
                    <li class="nav-item">
                        <a href="{{ path('app_logout') }}" class="nav-link"><i class="fas fa-sign-in-alt"></i> Выйти</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{{ path('app_login') }}" class="nav-link"><i class="fas fa-sign-in-alt"></i> Вход</a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ path('signup') }}" class="nav-link"><i class="fas fa-user-plus"></i> Регистрация</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>


<div class="container">
    {% block body %}
    {% endblock %}
</div>


<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6">
                <span class="text-muted">Тестовое задание по Symfony</span>
            </div>
            <div class="col-12 col-md-6 date-block">
                <span class="text-muted">{{ "now"|date('d.m.Y') }}</span>
            </div>
        </div>
    </div>
</footer>


{% block javascripts %}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
{% endblock %}
</body>
</html>